accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
]

board/urls.py
from django.urls import path
from . import views
app_name='board'

urlpatterns = [
    path('' , views.index, name='index'),
    path('create/', views.create, name='create'),

    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/create/c', views.create_c, name='create_c'),
    path('<int:p_id>/delete/<int:c_id>/', views.delete_c, name='delete_c'),

    path('search/', views.search, name='search'),
    
    path('<int:id>/like/', views.like, name="like" ),
    path('<int:p_id>/like/<int:c_id>/', views.like_c, name="like_c")
]

cafe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

board/models.py
# Create your models here.
from django.db import models
from django.conf import settings

# Create your models here.

class P(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")

class C(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    p = models.ForeignKey(P,on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    like_users_c = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_comment")

board/forms.py
from django import forms
from .models import P,C

class PForm(forms.ModelForm):
    class Meta:
        model = P
        fields=('title','content',)

class CForm(forms.ModelForm):
    class Meta:
        model = C
        fields=('content',)
        widgets = {
            'content':forms.TextInput(
                attrs={
                    'placeholder':'comment',
                }
            ),
        }
        labels = {
            'content':'comment',
        }
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('board:index')
    
    if request.method =="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            auth_login(request,user)
            return redirect('board:index')
    
    else:
        form = UserCreationForm()
    context={
        'form':form
    }
    return render(request, 'accounts/form.html',context)

def login(request):
    if request.user.is_authenticated:
        return redirect('board:index')
    
    if request.method =="POST":
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect('board:index')
    else:
        form=AuthenticationForm()
    
    context={
        'form':form
    }
    return render(request,'accounts/form.html',context)

def logout(request):
    auth_logout(request)
    return redirect('board:index')

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import P,C
from .forms import PForm,CForm
# Create your views here.
@login_required
def index(request):
    ps = P.objects.all()
    context={
        'ps':ps
    }
    return render(request,'board/index.html',context)
    
def search(request):
    ps = P.objects.all()
    search = request.GET.get('search')
    context={
        'search':search,
        'ps':ps
    }
    return render(request,'board/search.html',context)

@login_required
def create(request):
    if request.method == "POST":
        form = PForm(request.POST)
        if form.is_valid():
            p = form.save(commit=False)
            p.author = request.user
            p.save()
            return redirect('board:index')
    
    else:
        form = PForm()
    context= {
        'form':form
    }
    return render(request,'board/form.html',context)

@login_required
def detail(request, id):
    p = get_object_or_404(P,id=id)
    cform = CForm()
    context={
        'p':p,
        'cform':cform
    }
    return render(request,'board/detail.html',context)

@login_required
def update(request, id):
    p = get_object_or_404(P, id= id)
    if request.user == p.author:
        if request.method =="POST":
            form = PForm(request.POST, instance=p)
            if form.is_valid():
                form.save()
                return redirect('board:detail', id)
        else:
            form = PForm(instance=p)
        context={
            'form':form
        }
        return render(request,'board/form.html', context)
    return redirect('board:detail', id)

@login_required
def delete(request, id):
    p = get_object_or_404(P, id= id)
    if request.user == p.author:
        p.delete()
    return redirect('board:index') 

@login_required
def create_c(request, id):
    if request.method =="POST":
        cform = CForm(request.POST)
        if cform.is_valid():
            c = cform.save(commit=False)
            c.author = request.user
            c.p = get_object_or_404(P, id=id)
            c.save()
            return redirect('board:detail',id)

    return redirect('board:detail',id)

@login_required
def delete_c(request, p_id, c_id):
    c = get_object_or_404(C, id=c_id)
    if c.author == request.user:
        c.delete()
    return redirect('board:detail', p_id) 

@login_required
def like(request,id):
    p = get_object_or_404(P,id=id)
    user = request.user
    if user in p.like_users.all():
        p.like_users.remove(user)
    else:
        p.like_users.add(user)

    return redirect('board:detail',id)

@login_required
def like_c(request, p_id, c_id):
    c = get_object_or_404(C,id=c_id)
    user = request.user
    if user in c.like_users_c.all():
        c.like_users_c.remove(user)
    else:
        c.like_users_c.add(user)

    return redirect('board:detail', p_id)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock %}

board/templates/board/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <div class="jumbotron jumbotron-fluid my-2">
    <div class="container">
      <h1 class="display-5">{{p.title}}</h1>
      <p class="text-muted text-right">'{{p.author}}'님이 {{p.created_at}} 작성하신 글 입니다. </p>
      <p class="text-muted text-right"> </p>
      <hr class="my-4">
      <p class="lead">{{p.content}}</p>

      {% if user in p.like_users.all %}
        <a href="{% url 'board:like' p.id %}" class="btn btn-success">좋아요 취소</a>
      {% else %}
        <a href="{% url 'board:like' p.id %}" class="btn btn-success">좋아요!!</a>
      {% endif %}
      <p>추천수:({{p.like_users.all.count}})</p>
    </div>
    {% if p.author ==  request.user %}
      <div class="d-flex justify-content-end">
        <a class = "btn btn-outline-secondary mr-2" href="{% url 'board:update' p.id %}">수정</a>
        <a class = "btn btn-outline-danger mr-3" href="{% url 'board:delete' p.id %}">삭제</a>
      </div>
    {% endif %}
  </div>

  
  <form action="{% url 'board:create_c' p.id %}" method="post">
    {% csrf_token %}
    <div class = "row">
      <div class = "col-11 my-2">
        {% bootstrap_form cform layout='horizontal' %}
      </div>
      <input class ="btn btn-outline-primary float-right mt-2 mb-4 ml-4" type="submit" value="작성">
    </div>
  </form>

  {% for c in p.c_set.all %}
    <button type="button" class="btn btn-outline-secondary btn-block text-left">
      
      {{c.author}} : {{c.content}}


      {% if user in c.like_users_c.all %}
        <a href="{% url 'board:like_c' p.id c.id  %}" class="btn btn-warning " >댓글 좋아요 취소 </a>
      {% else %}
        <a href="{% url 'board:like_c' p.id c.id %}" class="btn btn-info ">이 댓글이 좋아요!! </a>
      {% endif %}
      <p class="inline">추천수: ({{c.like_users_c.all.count}})</p>
      {% if c.author ==  request.user %}
        <a class = "float-right btn btn-outline-dark btn-sm float-right" href="{% url 'board:delete_c' p.id c.id %}">삭제</a>
      {% endif %}
    </button>
  {% endfor %}
{% endblock %}

board/templates/board/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1 class ="text-center">목록</h1>
  {% for p in ps %}
    <div class="alert alert-secondary row" role="alert">
        <a href="{% url 'board:detail' p.id %}" class="alert-link col-9 my-2">{{p.title}}</a>
        <p class="text-right text-muted col-3 my-2">{{p.author}}-{{p.created_at}}</p>
    </div>
  {% endfor %}
{% endblock %}  

board/templates/board/search.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1 class ="text-center">목록</h1>
  {% for p in ps %}
    {% if search in p.content or search in p.title or search in p.author %}
      <div class="alert alert-secondary row" role="alert">
          <a href="{% url 'board:detail' p.id %}" class="alert-link col-9 my-2">{{p.title}}</a>
          <p class="text-right text-muted col-3 my-2">{{p.author}}-{{p.created_at}}</p>
      </div>
    {% else %}
    {% endif %}
  {% endfor %}
{% endblock %}  

cafe/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=DM+Serif+Text|Yeon+Sung&display=swap" rel="stylesheet">
  {% bootstrap_css %}
  <style>
    li {
      font-family: 'DM Serif Text', serif;
    }
    div {
      font-family: 'Yeon Sung', cursive;
    }
  </style>
</head>
<body>
  <ul class="nav justify-content-end navbar-dark bg-dark mb-5">
    <li class="nav-item">
      <a class="nav-link active text-white" href="{% url 'board:index' %}">Home</a>
    </li>
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'board:create' %}">Write</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user.username}}님 안녕하세요!</a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'accounts:signup' %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'accounts:login' %}">Login</a>
      </li>
    {% endif %}
    <li>
      <form action="{% url 'board:search' %}" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </li>
  </ul>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>